const QBF_URL='https://zzvqruhfgjocnwffavcb.supabase.co';
const QBF_KEY='sb_publishable_-nq-Po_ytT0E6uM8vmp1zw_FPftRDVN';
const qbf=window.supabase.createClient(QBF_URL,QBF_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
const qbfScreen=document.querySelector('#screen');
const qbfEsc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qbfTab=()=>document.querySelector('#mainNav button.active')?.textContent?.trim()||'';
let qbfTimer=null,qbfBusy=false;
function qbfMeta(v){return v&&typeof v==='object'?v:{}}
function qbfStats(m){m=qbfMeta(m);const a=[];if(m.defense)a.push(`+${m.defense} Defense`);if(m.ward_pct)a.push(`+${m.ward_pct}% Ward`);if(m.fortune)a.push(`+${m.fortune} Fortune`);if(m.training_xp_pct)a.push(`+${m.training_xp_pct}% Training XP`);if(m.exploration_xp_pct)a.push(`+${m.exploration_xp_pct}% Exploration XP`);if(m.third_expedition_renown)a.push(`+${m.third_expedition_renown} Renown every 3rd expedition`);if(m.gauntlet_xp_pct)a.push(`+${m.gauntlet_xp_pct}% Gauntlet XP`);if(m.witcher_trial_xp_pct)a.push(`+${m.witcher_trial_xp_pct}% Witcher Trial XP`);return a.join(' · ')}
async function qbfIdentity(){const {data:{session}}=await qbf.auth.getSession();if(!session)return null;const {data:membership}=await qbf.from('guild_members').select('guild_id,user_id,player_key,role').eq('user_id',session.user.id).maybeSingle();if(!membership)return null;const {data:members=[]}=await qbf.from('guild_members').select('guild_id,user_id,player_key,role').eq('guild_id',membership.guild_id);return{session,membership,members}}
function qbfToast(msg){let t=document.querySelector('#qbfToast');if(!t){t=document.createElement('div');t.id='qbfToast';t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function qbfCutRoadMarch(){qbfScreen?.querySelectorAll('.road-block').forEach(x=>x.remove());document.querySelectorAll('button').forEach(b=>{if(/steps|road march/i.test(b.textContent||''))b.remove()})}
async function qbfGearStats(id){if(qbfTab()!=='Character')return;const active=[...qbfScreen.querySelectorAll('.qb-character-switch button.active')][0]?.textContent?.trim()||id.membership.player_key;if(active!==id.membership.player_key)return;const [{data:items=[]},{data:defs=[]}]=await Promise.all([qbf.from('player_items').select('*').eq('guild_id',id.membership.guild_id).eq('owner_user_id',id.session.user.id).neq('state','discarded'),qbf.from('item_definitions').select('*').eq('active',true)]);const imap=Object.fromEntries(items.map(i=>[i.id,i])),dmap=Object.fromEntries(defs.map(d=>[d.key,d]));qbfScreen.querySelectorAll('.gear-slot').forEach(slot=>{if(slot.querySelector('.qbf-gear-stats'))return;const btn=slot.querySelector('[data-item-id]');if(!btn)return;const i=imap[btn.dataset.itemId],d=i&&dmap[i.item_key],txt=qbfStats(d?.mechanics||qbfMeta(i?.metadata).mechanics);if(txt){const s=document.createElement('span');s.className='qbf-gear-stats';s.textContent=txt;slot.appendChild(s)}});qbfScreen.querySelectorAll('.qb-pack-item').forEach(row=>{if(row.querySelector('.qbf-gear-stats'))return;const btn=row.querySelector('[data-item-id]');if(!btn)return;const i=imap[btn.dataset.itemId],d=i&&dmap[i.item_key],txt=qbfStats(d?.mechanics||qbfMeta(i?.metadata).mechanics);if(txt){const s=document.createElement('span');s.className='qbf-gear-stats';s.textContent=txt;row.querySelector(':scope > div:first-child')?.appendChild(s)}if(i?.state==='pack'&&d?.kind!=='gear'&&!row.querySelector('[data-qbf-use]')){const actions=row.querySelector('.qb-pack-actions');if(actions){const use=document.createElement('button');use.dataset.qbfUse=i.id;use.textContent=d?.kind==='challenge'?'Use · Throw Gauntlet':'Use Item';use.onclick=async()=>{const {data,error}=await qbf.rpc('use_player_item',{p_item_id:i.id});if(error)return alert(error.message);qbfToast(data?.kind==='gauntlet'?`🥊 Gauntlet thrown: ${data.objective}`:`✓ ${data?.name||d?.name||'Item'} activated`);document.querySelector('#mainNav button.active')?.click()};actions.prepend(use)}}})}
async function qbfGuildInventory(id){if(qbfTab()!=='Guild')return;const [{data:items=[]},{data:defs=[]},{data:campaigns=[]}]=await Promise.all([qbf.from('guild_items').select('*').eq('guild_id',id.membership.guild_id).order('created_at',{ascending:false}),qbf.from('item_definitions').select('*').eq('active',true),qbf.from('campaigns').select('id,name,status,archived_at').eq('guild_id',id.membership.guild_id).eq('status','archived')]);const dmap=Object.fromEntries(defs.map(d=>[d.key,d]));let vault=[...qbfScreen.querySelectorAll('.card')].find(c=>/guild vault|party effects/i.test(c.textContent||''));if(vault&&!vault.querySelector('#qbfSharedInventory')){const box=document.createElement('div');box.id='qbfSharedInventory';box.innerHTML=`<div class="qbf-subhead"><b>🎒 Shared Inventory</b><span>${items.reduce((n,x)=>n+Number(x.quantity||0),0)} item(s)</span></div><div class="qbf-vault-grid">${Array.from({length:6},(_,n)=>{const i=items[n];if(!i)return'<div class="qbf-vault-slot empty">·</div>';const d=dmap[i.item_key]||{},name=qbfMeta(i.metadata).name||d.name||i.item_key,desc=qbfMeta(i.metadata).description||d.description||'',stat=qbfStats(d.mechanics||qbfMeta(i.metadata).effect||i.metadata);return `<div class="qbf-vault-slot"><b>${qbfEsc(name)}${Number(i.quantity||1)>1?` ×${i.quantity}`:''}</b><span>${qbfEsc(desc)}</span>${stat?`<small>${qbfEsc(stat)}</small>`:''}</div>`}).join('')}</div><p class="fine">Shared-use consumables and Party effects live here. Personal gear stays in Character → Pack.</p>`;vault.appendChild(box)}if(!qbfScreen.querySelector('#qbfGuildAchievements')){const card=document.createElement('section');card.id='qbfGuildAchievements';card.className='card home-card';card.innerHTML=`<p class="eyebrow">🏆 TROPHY ROOM</p><h2>Achievements</h2><div class="qb-achievement-grid">${campaigns.length?`<span>🏆 ${campaigns.length} Campaign ${campaigns.length===1?'Victory':'Victories'}</span>`:'<span>Major Guild achievements will appear here.</span>'}</div>`;const grid=qbfScreen.querySelector('.qb-guild-grid')||qbfScreen.querySelector('.home-two')||qbfScreen;grid.appendChild(card)}}
function qbfDeduplicateAdmin(){if(qbfTab()!=='Guild Admin')return;const beta=qbfScreen.querySelector('#qbBetaConsole');if(beta){[...qbfScreen.querySelectorAll('.card')].forEach(c=>{if(c===beta||beta.contains(c))return;if(/prototype only|gm console/i.test(c.textContent||''))c.remove()});beta.querySelector('#qbFiveSteps')?.remove();[...beta.querySelectorAll('button')].filter(b=>/steps|road march/i.test(b.textContent||'')).forEach(b=>b.remove())}qbfCutRoadMarch()}
async function qbfHallClick(id,campaignName){const {data:campaign}=await qbf.from('campaigns').select('*').eq('guild_id',id.membership.guild_id).eq('status','archived').ilike('name',campaignName).order('archived_at',{ascending:false}).limit(1).maybeSingle();if(!campaign)return;const {data:contrib=[]}=await qbf.from('campaign_contributions').select('*').eq('campaign_id',campaign.id);const names=Object.fromEntries(id.members.map(m=>[m.user_id,m.player_key])),by=Object.fromEntries(contrib.map(c=>[names[c.user_id]||'Player',Number(c.campaign_xp||0)]));const start=campaign.started_at?new Date(campaign.started_at):null,end=campaign.completed_at?new Date(campaign.completed_at):null,days=start&&end?Math.max(1,Math.ceil((end-start)/86400000)):null;const modal=document.createElement('div');modal.className='qbf-modal';modal.innerHTML=`<div class="qbf-dialog"><div class="card-head"><div><p class="eyebrow">CAMPAIGN ARCHIVE</p><h2>${qbfEsc(campaign.name)}</h2></div><button data-close class="ghost">✕</button></div><div class="qbf-campaign-stats"><div><b>${Number(campaign.campaign_xp||0).toLocaleString()}</b><span>Campaign XP</span></div><div><b>${end?end.toLocaleDateString():'—'}</b><span>Completed</span></div><div><b>${Number(by.Kate||0).toLocaleString()}</b><span>Kate contribution</span></div><div><b>${Number(by.Drew||0).toLocaleString()}</b><span>Drew contribution</span></div>${days?`<div><b>${days}</b><span>Days on campaign</span></div>`:''}</div><h3>Chapters Crossed</h3><p class="qbf-chapters">The Road from Home → The Prancing Lantern → Council at the Crossroads → Beneath the Mountain → Through the Deadlands → Ascending the Burning Mountain → The Burden Ends</p></div>`;document.body.appendChild(modal);modal.querySelector('[data-close]').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()}}
function qbfHallAchievements(){if(qbfTab()!=='Hall of History'||qbfScreen.querySelector('#qbfHallAchievements'))return;const s=document.createElement('section');s.id='qbfHallAchievements';s.className='card home-card';s.innerHTML='<p class="eyebrow">🏅 MAJOR ACHIEVEMENTS</p><h2>Guild Milestones</h2><div class="qb-achievement-grid"><span>Campaign victories and major achievements are preserved here.</span></div>';qbfScreen.appendChild(s)}
async function qbfEnhance(){if(qbfBusy||!qbfScreen)return;qbfBusy=true;try{const id=await qbfIdentity();if(!id)return;qbfCutRoadMarch();await qbfGearStats(id);await qbfGuildInventory(id);qbfDeduplicateAdmin();qbfHallAchievements()}catch(e){console.warn('Questbound feature fixes:',e)}finally{qbfBusy=false}}
function qbfSchedule(){clearTimeout(qbfTimer);qbfTimer=setTimeout(qbfEnhance,520)}
const Native=window.__QB_NATIVE_MUTATION_OBSERVER||window.MutationObserver;const qbfObserver=new Native(()=>qbfSchedule());if(qbfScreen)qbfObserver.observe(qbfScreen,{childList:true,subtree:true});document.querySelector('#mainNav')?.addEventListener('click',qbfSchedule,{capture:true});setTimeout(qbfEnhance,900);
document.addEventListener('click',async e=>{if(qbfTab()!=='Hall of History')return;const trophy=e.target.closest('.trophy,[data-campaign]');if(!trophy)return;const id=await qbfIdentity();if(!id)return;let name=trophy.querySelector('b')?.textContent?.trim()||'';name=name.replace(/^Victory:\s*/i,'').trim();if(name)qbfHallClick(id,name)},true);
